"use client"

import Link from "next/link"
import * as Dialog from "@radix-ui/react-dialog"
import { useCallback, useEffect, useState } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { Bell, BriefcaseBusiness, CalendarDays, Check, ChevronDown, ChevronRight, CircleDollarSign, CircleHelp, ClipboardCheck, Command, Home, Inbox, LogOut, Menu, MessageSquare, PanelLeftClose, PanelLeftOpen, Search, Settings2, ShieldCheck, Sparkles, Stethoscope, Users, X } from "lucide-react"
import type { CandidateEngagement, WorkspaceState, WorkspaceUser } from "@/lib/workspace/types"
import { calculateOccurrenceReadiness, requirementCoverage } from "@/lib/workspace/domain"

type Props = { initialActorId: string; initialState: WorkspaceState; initialSessionReady: boolean; view: string; recordId?: string }
type NavItem = { href: string; label: string; icon: typeof Home; section: "Plan" | "Work" | "Account" }

const money = (minor: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(minor / 100)
const date = (iso: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(iso))
const stage = (value: string) => value.replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase())

function defaultRoute(user: WorkspaceUser) {
  if (user.role === "manager") return `/clinic/${user.organisationId}/today`
  if (user.role === "doctor") return "/doctor/today"
  if (user.role === "approver") return "/approver/reviews"
  if (user.role === "finance") return "/finance/reconciliation"
  return "/operations/cases"
}

function navigation(user: WorkspaceUser): NavItem[] {
  if (user.role === "manager") return [
    { href: `/clinic/${user.organisationId}/today`, label: "Today", icon: Home, section: "Plan" },
    { href: `/clinic/${user.organisationId}/hiring/vacancies`, label: "Vacancies", icon: BriefcaseBusiness, section: "Work" },
    { href: `/clinic/${user.organisationId}/hiring/candidates`, label: "Candidates", icon: Users, section: "Work" },
    { href: `/clinic/${user.organisationId}/hiring/offers`, label: "Offers", icon: CircleDollarSign, section: "Work" },
    { href: `/clinic/${user.organisationId}/doctors`, label: "Doctors", icon: Search, section: "Work" },
    { href: `/clinic/${user.organisationId}/bookings`, label: "Bookings", icon: CalendarDays, section: "Plan" },
    { href: `/clinic/${user.organisationId}/inbox`, label: "Inbox", icon: Inbox, section: "Work" },
  ]
  if (user.role === "doctor") return [
    { href: "/doctor/today", label: "Today", icon: Home, section: "Plan" },
    { href: "/doctor/find-work", label: "Find work", icon: Search, section: "Work" },
    { href: "/doctor/bookings", label: "Bookings", icon: CalendarDays, section: "Work" },
    { href: "/doctor/inbox", label: "Inbox", icon: Inbox, section: "Work" },
    { href: "/onboarding/doctor", label: "Profile", icon: Stethoscope, section: "Account" },
  ]
  return [{ href: defaultRoute(user), label: user.role === "approver" ? "My reviews" : user.role === "finance" ? "Reconciliation" : "Cases", icon: user.role === "approver" ? ClipboardCheck : user.role === "finance" ? CircleDollarSign : ShieldCheck, section: "Work" }]
}

function activeNavigation(view: string, item: NavItem) { return view.includes(item.label.toLowerCase().replace(" ", "-")) || (item.label === "Today" && view.includes("today")) || (item.label === "Offers" && view === "offer") }

function WorkspaceLinks({ items, view, query = "", onNavigate }: { items: NavItem[]; view: string; query?: string; onNavigate?: () => void }) {
  const visible = items.filter((item) => item.label.toLowerCase().includes(query.trim().toLowerCase()))
  const sections = [...new Set(visible.map((item) => item.section))]
  return <>{sections.map((section) => <div className="df-nav-section" key={section}><span className="df-nav-label">{section}</span><nav aria-label={`${section} navigation`}>{visible.filter((item) => item.section === section).map((item) => <Link title={item.label} aria-label={item.label} aria-current={activeNavigation(view, item) ? "page" : undefined} className={activeNavigation(view, item) ? "active" : ""} href={item.href} key={item.href} onClick={onNavigate}><item.icon size={19} /><span>{item.label}</span><i aria-hidden="true" /></Link>)}</nav></div>)}</>
}

function Status({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "success" | "warning" | "info" | "danger" }) {
  return <span className={`df-status ${tone}`}>{children}</span>
}

function Empty({ title, detail }: { title: string; detail: string }) { return <div className="df-empty"><Search size={22} /><strong>{title}</strong><span>{detail}</span></div> }

export function SapphireWorkspace({ initialActorId, initialState, initialSessionReady, view, recordId }: Props) {
  const [state, setState] = useState(initialState)
  const [actorId, setActorId] = useState(initialActorId)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")
  const [sessionReady, setSessionReady] = useState(initialSessionReady)
  const [navigationCollapsed, setNavigationCollapsed] = useState(false)
  const [navigationQuery, setNavigationQuery] = useState("")
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [commandOpen, setCommandOpen] = useState(false)
  const [commandQuery, setCommandQuery] = useState("")
  const router = useRouter()
  const actor = state.users.find((item) => item.id === actorId) ?? state.users[0]
  const organisation = state.organisations.find((item) => item.id === actor.organisationId)
  const navigationItems = navigation(actor)
  const mobileItems = actor.role === "manager" ? navigationItems.filter((item) => ["Today", "Candidates", "Doctors", "Bookings", "Inbox"].includes(item.label)) : navigationItems.slice(0, 5)

  useEffect(() => {
    if (!initialSessionReady) void fetch("/api/v1/prototype/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId: initialActorId }) }).then((response) => setSessionReady(response.ok))
  }, [initialActorId, initialSessionReady])

  useEffect(() => {
    function shortcut(event: KeyboardEvent) { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen(true) } }
    window.addEventListener("keydown", shortcut)
    return () => window.removeEventListener("keydown", shortcut)
  }, [])

  const refresh = useCallback(async function refresh() {
    const response = await fetch("/api/v1/workspace/state", { cache: "no-store" })
    const result = await response.json()
    if (result.success) setState(result.data)
  }, [])

  async function switchActor(nextId: string) {
    const response = await fetch("/api/v1/prototype/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId: nextId }) })
    if (!response.ok) return
    const next = state.users.find((item) => item.id === nextId)
    if (!next) return
    setActorId(nextId)
    router.push(defaultRoute(next))
    router.refresh()
  }

  async function command(commandName: string, targetId: string, expectedVersion: number, payload?: Record<string, unknown>) {
    setBusy(true); setError("")
    const response = await fetch("/api/v1/workflow/command", { method: "POST", headers: { "content-type": "application/json", "Idempotency-Key": crypto.randomUUID(), "Expected-Version": String(expectedVersion) }, body: JSON.stringify({ command: commandName, recordId: targetId, payload }) })
    const result = await response.json()
    if (!result.success) setError(result.error.message)
    else await refresh()
    setBusy(false)
    return result
  }

  async function resetDemo() {
    if (!window.confirm("Reset all fictional Doc+Find demonstration data?")) return
    await fetch("/api/v1/prototype/reset", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation: "RESET DOC+FIND DEMO" }) })
    await refresh()
    router.push(defaultRoute(actor))
  }

  return <div className={`df-shell ${navigationCollapsed ? "is-navigation-collapsed" : ""}`} data-ui="sapphire-workspace">
    <aside className="df-sidebar">
      <Link href={defaultRoute(actor)} className="df-brand" aria-label="Doc+Find home"><span>Doc</span><b>+</b><span>Find</span></Link>
      <button className="df-collapse-navigation" type="button" aria-label={navigationCollapsed ? "Expand navigation" : "Collapse navigation"} onClick={() => setNavigationCollapsed((current) => !current)}>{navigationCollapsed ? <PanelLeftOpen size={17} /> : <PanelLeftClose size={17} />}</button>
      <div className="df-context"><span className="df-workspace-icon">{organisation?.name.slice(0, 1) ?? "D"}</span><div><small>Clinical workspace</small><strong>{organisation?.name ?? actor.roleLabel}</strong><span>All permitted sites</span></div><ChevronDown size={15} /></div>
      <div className="df-nav-search"><Search size={16} /><input value={navigationQuery} onChange={(event) => setNavigationQuery(event.target.value)} aria-label="Filter workspace navigation" placeholder="Find a view" /></div>
      <div className="df-sidebar-scroll"><WorkspaceLinks items={navigationItems} view={view} query={navigationQuery} /></div>
      <details className="df-demo-tools"><summary><Sparkles size={15} /><span>Demo tools</span></summary><div><span>Prototype only</span><label htmlFor="demo-identity">View as</label><select id="demo-identity" disabled={!sessionReady} value={actor.id} onChange={(event) => switchActor(event.target.value)}>{state.users.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.roleLabel}</option>)}</select><button type="button" disabled={!sessionReady} onClick={resetDemo}><Settings2 size={16} /> Reset demo data</button></div></details>
    </aside>
    <div className="df-main">
      <header className="df-topbar"><button className="df-mobile-menu-trigger" type="button" aria-label="Open workspace menu" onClick={() => setMobileMenuOpen(true)}><Menu size={22} /></button><Link href={defaultRoute(actor)} className="df-mobile-brand">Doc<span>+</span>Find</Link><button className="df-global-search" type="button" onClick={() => setCommandOpen(true)}><Search size={18} /><span>Search views and records</span><kbd>⌘ K</kbd></button><div className="df-top-actions"><span className="df-demo-badge"><Sparkles size={14} /> Demo data</span><button type="button" aria-label="Help and support"><CircleHelp size={19} /></button><Link href={actor.role === "doctor" ? "/doctor/inbox" : actor.role === "manager" ? `/clinic/${actor.organisationId}/inbox` : defaultRoute(actor)} aria-label="Notifications"><Bell size={19} /><i>{state.notifications.filter((item) => item.recipientId === actor.id && !item.readAt).length}</i></Link><span className="df-avatar">{actor.initials}</span></div></header>
      {error && <div className="df-error" role="alert">{error}<button type="button" onClick={() => setError("")}>Dismiss</button></div>}
      <main className="df-content">
        {view === "clinic-today" && <ClinicToday state={state} actor={actor} />}
        {view === "clinic-vacancies" && <Vacancies state={state} actor={actor} busy={busy} command={command} />}
        {view === "clinic-candidates" && <Candidates state={state} actor={actor} busy={busy} command={command} />}
        {view === "clinic-offers" && <Offers state={state} actor={actor} />}
        {view === "clinic-doctors" && <Doctors state={state} actor={actor} busy={busy} command={command} />}
        {view === "doctor-today" && <DoctorToday state={state} actor={actor} />}
        {view === "doctor-find-work" && <FindWork state={state} actor={actor} busy={busy} command={command} />}
        {view === "doctor-bookings" && <Bookings state={state} actor={actor} busy={busy} command={command} />}
        {view === "clinic-bookings" && <ClinicBookings state={state} actor={actor} busy={busy} command={command} />}
        {view === "clinic-inbox" && <InboxView state={state} actor={actor} />}
        {view === "inbox" && <InboxView state={state} actor={actor} />}
        {view === "engagement" && recordId && <EngagementView state={state} actor={actor} engagementId={recordId} onRefresh={refresh} />}
        {view === "offer" && recordId && <OfferView state={state} actor={actor} offerId={recordId} busy={busy} command={command} />}
        {view === "approver" && <ApproverView state={state} busy={busy} command={command} />}
        {view === "finance" && <FinanceView state={state} busy={busy} command={command} />}
        {view === "operations" && <OperationsView state={state} />}
        {view === "onboarding" && <OnboardingView state={state} actor={actor} audience={recordId === "clinic" ? "clinic" : "doctor"} onRefresh={refresh} />}
      </main>
      <nav className="df-mobile-nav" aria-label="Mobile navigation">{mobileItems.map((item) => <Link className={activeNavigation(view, item) ? "active" : ""} aria-current={activeNavigation(view, item) ? "page" : undefined} aria-label={item.label} href={item.href} key={item.href}><item.icon size={20} /><span>{item.label}</span></Link>)}</nav>
    </div>
    <WorkspaceMenu open={mobileMenuOpen} onOpenChange={setMobileMenuOpen} actor={actor} organisation={organisation?.name} items={navigationItems} view={view} query={navigationQuery} setQuery={setNavigationQuery} />
    <CommandPalette open={commandOpen} onOpenChange={setCommandOpen} query={commandQuery} setQuery={setCommandQuery} state={state} actor={actor} items={navigationItems} view={view} />
  </div>
}

function WorkspaceMenu({ open, onOpenChange, actor, organisation, items, view, query, setQuery }: { open: boolean; onOpenChange: (value: boolean) => void; actor: WorkspaceUser; organisation?: string; items: NavItem[]; view: string; query: string; setQuery: (value: string) => void }) {
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="df-dialog-overlay" /><Dialog.Content className="df-mobile-menu"><Dialog.Title className="df-menu-title">Doc<b>+</b>Find</Dialog.Title><Dialog.Description className="df-menu-description">Navigate {organisation ?? actor.roleLabel}</Dialog.Description><Dialog.Close className="df-dialog-close" aria-label="Close workspace menu"><X size={20} /></Dialog.Close><div className="df-mobile-context"><span className="df-workspace-icon">{organisation?.slice(0, 1) ?? actor.initials.slice(0, 1)}</span><div><strong>{organisation ?? actor.name}</strong><span>{actor.roleLabel}</span></div></div><div className="df-nav-search mobile"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Filter workspace navigation" placeholder="Find a page" /></div><div className="df-mobile-menu-links"><WorkspaceLinks items={items} view={view} query={query} onNavigate={() => onOpenChange(false)} /></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}

function CommandPalette({ open, onOpenChange, query, setQuery, state, actor, items, view }: { open: boolean; onOpenChange: (value: boolean) => void; query: string; setQuery: (value: string) => void; state: WorkspaceState; actor: WorkspaceUser; items: NavItem[]; view: string }) {
  const term = query.trim().toLowerCase()
  const records = actor.role === "manager" ? state.engagements.filter((eng) => { const doctor = state.doctors.find((item) => item.id === eng.doctorId); const req = state.requirements.find((item) => item.id === eng.requirementId); return !term || `${doctor?.name} ${req?.title}`.toLowerCase().includes(term) }).slice(0, 5) : []
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="df-dialog-overlay" /><Dialog.Content className="df-command-palette"><Dialog.Title><Command size={19} /> Search Doc+Find</Dialog.Title><Dialog.Description>Open an authorised view or candidate record.</Dialog.Description><Dialog.Close className="df-dialog-close" aria-label="Close search"><X size={20} /></Dialog.Close><label className="df-command-input"><Search size={19} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search views, doctors or vacancies" /></label><div className="df-command-results"><span>Views</span><WorkspaceLinks items={items} view={view} query={query} onNavigate={() => onOpenChange(false)} />{actor.role === "manager" && <><span>Candidate records</span>{records.map((eng) => { const doctor = state.doctors.find((item) => item.id === eng.doctorId); const req = state.requirements.find((item) => item.id === eng.requirementId); return <Link key={eng.id} href={`/clinic/${actor.organisationId}/hiring/candidates?candidateId=${eng.id}&stage=all`} onClick={() => onOpenChange(false)}><span className="df-avatar small">{doctor?.initials}</span><div><strong>{doctor?.name}</strong><small>{req?.title}</small></div><ChevronRight size={17} /></Link> })}</>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
}

function PageTitle({ eyebrow, title, detail, actions }: { eyebrow: string; title: string; detail: string; actions?: React.ReactNode }) {
  const Icon = /doctor|onboarding|opportunit|schedule/i.test(eyebrow) ? Stethoscope : /message|communication/i.test(eyebrow) ? MessageSquare : /finance/i.test(eyebrow) ? CircleDollarSign : /governance|operations/i.test(eyebrow) ? ShieldCheck : BriefcaseBusiness
  return <div className="df-page-title"><div className="df-title-cluster"><span className="df-page-icon" aria-hidden="true"><Icon size={20} /></span><div><span className="df-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{detail}</p></div></div>{actions}</div>
}

function HiringNav({ actor, active }: { actor: WorkspaceUser; active: "vacancies" | "candidates" | "offers" }) {
  const root = `/clinic/${actor.organisationId}/hiring`
  return <nav className="df-view-nav" aria-label="Hiring views"><Link className={active === "vacancies" ? "active" : ""} href={`${root}/vacancies`}>Vacancies</Link><Link className={active === "candidates" ? "active" : ""} href={`${root}/candidates`}>Candidates</Link><Link className={active === "offers" ? "active" : ""} href={`${root}/offers`}>Offers</Link></nav>
}

function GroupHeader({ tone, title, count }: { tone: "blue" | "purple" | "green"; title: string; count: number }) {
  return <div className={`df-group-header ${tone}`}><span aria-hidden="true" /><strong>{title}</strong><small>{count}</small></div>
}

function EngagementLifecycle({ state, engagement }: { state: WorkspaceState; engagement: CandidateEngagement }) {
  const offers = state.offers.filter((item) => item.engagementId === engagement.id)
  const booking = state.bookings.find((item) => item.engagementId === engagement.id)
  const payment = state.payments.find((item) => item.bookingId === booking?.id)
  const occurrenceStates = booking?.occurrenceIds.map((id) => state.occurrences.find((item) => item.id === id)?.state) ?? []
  const readiness = booking?.occurrenceIds.map((id) => calculateOccurrenceReadiness(state, engagement.doctorId, id)) ?? []
  const rank: Record<CandidateEngagement["stage"], number> = { invited: 0, applied: 0, shortlisted: 1, in_discussion: 1, offer_sent: 2, terms_accepted: 3, declined: 2, withdrawn: 1 }
  const reached = rank[engagement.stage]
  const steps = [
    { label: engagement.origins.includes("application") ? "Applied" : "Invited", done: true },
    { label: "Conversation", done: reached >= 1 || state.messages.some((item) => state.conversations.find((conversation) => conversation.id === item.conversationId)?.engagementId === engagement.id) },
    { label: "Offer", done: offers.length > 0 },
    { label: "Accepted", done: engagement.stage === "terms_accepted" || Boolean(booking) },
    { label: "Ready", done: readiness.length > 0 && readiness.every((item) => item.state === "ready") },
    { label: "Complete", done: occurrenceStates.length > 0 && occurrenceStates.every((item) => item === "completed") },
    { label: "Paid", done: payment?.state === "paid" },
  ]
  const firstPending = steps.findIndex((item) => !item.done)
  return <ol className="df-lifecycle" aria-label="Engagement lifecycle">{steps.map((item, index) => <li className={item.done ? "complete" : index === firstPending ? "current" : ""} key={item.label}><span>{item.done ? <Check size={13} /> : index + 1}</span><small>{item.label}</small></li>)}</ol>
}

function ClinicToday({ state, actor }: { state: WorkspaceState; actor: WorkspaceUser }) {
  const reqs = state.requirements.filter((item) => item.organisationId === actor.organisationId)
  const notifications = state.notifications.filter((item) => item.recipientId === actor.id).toSorted((a, b) => b.createdAt.localeCompare(a.createdAt)); const unread = notifications.filter((item) => !item.readAt)
  return <><PageTitle eyebrow="Clinic workspace" title="Today" detail="Priorities for your staffing team, ordered by what needs attention." />
    <section className={unread.length ? "df-priority" : "df-priority success"}><div><span className="df-kicker">{unread.length ? "Needs attention" : "Up to date"}</span><h2>{unread.length ? `${unread.length} candidate updates to review` : "No unread candidate updates"}</h2><p>Open each candidate to acknowledge their application or message. They will see the first-view timestamp.</p></div><Link className="df-primary" href={`/clinic/${actor.organisationId}/inbox`}>Open communication centre <ChevronRight size={17} /></Link></section>
    <div className="df-grid-2"><section className="df-panel"><div className="df-section-head"><div><span>Open requirements</span><h2>Coverage at a glance</h2></div><Link href={`/clinic/${actor.organisationId}/hiring/vacancies`}>View all</Link></div>{reqs.map((req) => { const coverage = requirementCoverage(state, req.id); return <Link className="df-record" href={`/clinic/${actor.organisationId}/hiring/candidates?requirement=${req.id}`} key={req.id}><div><strong>{req.title}</strong><span>{state.sites.find((site) => site.id === req.siteId)?.name} · {coverage.label}</span></div><Status tone={req.status === "published" ? "success" : "neutral"}>{stage(req.status)}</Status></Link> })}</section>
      <section className="df-panel"><div className="df-section-head"><div><span>Candidate activity</span><h2>Recent updates</h2></div></div>{notifications.slice(0, 4).map((item) => <Link className="df-record" href={item.href} key={item.id}><div><strong>{item.title}</strong><span>{item.detail} · {item.readAt ? "Seen" : "Unread"} · {date(item.createdAt)}</span></div><ChevronRight size={18} /></Link>)}</section></div></>
}

function Vacancies({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const reqs = state.requirements.filter((item) => item.organisationId === actor.organisationId)
  return <><PageTitle eyebrow="Hiring workspace" title="Vacancies" detail={`${reqs.length} requirements across your authorised clinic sites.`} actions={<VacancyComposer state={state} actor={actor} busy={busy} command={command} />} /><HiringNav actor={actor} active="vacancies" /><section className="df-panel df-table-panel"><GroupHeader tone="blue" title="Clinic requirements" count={reqs.length} /><table className="df-table df-responsive-table"><thead><tr><th>Vacancy</th><th>Site</th><th>Coverage</th><th>Rate</th><th>Status</th></tr></thead><tbody>{reqs.map((req) => <tr key={req.id}><td data-label="Vacancy"><Link href={`/clinic/${actor.organisationId}/hiring/candidates?requirement=${req.id}`}><strong>{req.title}</strong><span>{req.scope}</span></Link></td><td data-label="Site">{state.sites.find((site) => site.id === req.siteId)?.name}</td><td data-label="Coverage">{requirementCoverage(state, req.id).label}</td><td data-label="Rate">{money(req.rateMinor)}</td><td data-label="Status"><Status tone={req.status === "published" ? "success" : "neutral"}>{stage(req.status)}</Status></td></tr>)}</tbody></table></section></>
}

function VacancyComposer({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [scope, setScope] = useState("Adult outpatient dermatology"); const [siteId, setSiteId] = useState(actor.siteIds[0] ?? ""); const [rate, setRate] = useState("600"); const [startsAt, setStartsAt] = useState("")
  async function publish() { const result = await command("publish", "new-requirement", 0, { title, scope, siteId, rateMinor: Number(rate) * 100, startsAt: startsAt ? [new Date(startsAt).toISOString()] : [] }); if ((result as { success?: boolean })?.success) { setOpen(false); setTitle(""); setStartsAt("") } }
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="df-primary" type="button">Create vacancy</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="df-dialog-overlay" /><Dialog.Content className="df-form-dialog"><Dialog.Title>Create a clinic vacancy</Dialog.Title><Dialog.Description>Publish a clear requirement doctors can review and apply to.</Dialog.Description><Dialog.Close className="df-dialog-close" aria-label="Close vacancy form"><X size={20} /></Dialog.Close><div className="df-dialog-form"><label>Vacancy title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Saturday dermatology cover" /></label><label>Clinic site<select value={siteId} onChange={(event) => setSiteId(event.target.value)}>{state.sites.filter((site) => actor.siteIds.includes(site.id)).map((site) => <option value={site.id} key={site.id}>{site.name}</option>)}</select></label><label>Clinical scope<input value={scope} onChange={(event) => setScope(event.target.value)} /></label><div className="df-form-row"><label>Rate per session<div className="df-money-input"><span>£</span><input inputMode="numeric" type="number" min="100" value={rate} onChange={(event) => setRate(event.target.value)} /></div></label><label>First session<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label></div><div className="df-dialog-note"><ShieldCheck size={17} /><span>Publishing creates a real demo requirement and notifies no doctor until they apply or are invited.</span></div><button disabled={busy || !title.trim() || !startsAt} className="df-primary" type="button" onClick={publish}>{busy ? "Publishing…" : "Publish vacancy"}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}

function Candidates({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const params = useSearchParams(); const router = useRouter(); const selected = params.get("candidateId"); const filter = params.get("stage") ?? "all"; const query = params.get("q") ?? ""
  const scopedEngagements = state.engagements.filter((eng) => state.requirements.find((req) => req.id === eng.requirementId)?.organisationId === actor.organisationId)
  const engagements = scopedEngagements.filter((eng) => filter === "all" || eng.stage === filter).filter((eng) => { const doctor = state.doctors.find((item) => item.id === eng.doctorId); const req = state.requirements.find((item) => item.id === eng.requirementId); return `${doctor?.name ?? ""} ${req?.title ?? ""}`.toLowerCase().includes(query.toLowerCase()) })
  const selectedEng = scopedEngagements.find((item) => item.id === selected)
  function updateQuery(value: string) { const next = new URLSearchParams(params.toString()); if (value) next.set("q", value); else next.delete("q"); next.delete("candidateId"); router.replace(`?${next.toString()}`) }
  const filterHref = (nextStage: string) => `?${new URLSearchParams({ ...(query ? { q: query } : {}), stage: nextStage }).toString()}`
  return <><PageTitle eyebrow="Hiring workspace" title="Candidates" detail={`${engagements.length} candidate engagement records. Applications and invitations share one record.`} /><HiringNav actor={actor} active="candidates" />
    <div className="df-filterbar"><Search size={18} /><input value={query} onChange={(event) => updateQuery(event.target.value)} aria-label="Search candidates" placeholder="Search name or vacancy" /><Link className={filter === "all" ? "selected" : ""} href={filterHref("all")}>All</Link><Link className={filter === "applied" ? "selected" : ""} href={filterHref("applied")}>New applications</Link><Link className={filter === "shortlisted" ? "selected" : ""} href={filterHref("shortlisted")}>Shortlisted</Link></div>
    <div className={`df-workbench ${selectedEng ? "has-detail" : ""}`}><section className="df-panel df-table-panel"><GroupHeader tone="purple" title="Candidate engagements" count={engagements.length} /><table className="df-table df-responsive-table"><thead><tr><th>Doctor</th><th>Vacancy</th><th>Origin</th><th>Dates</th><th>Stage</th><th>Last activity</th></tr></thead><tbody>{engagements.map((eng) => { const doctor = state.doctors.find((d) => d.id === eng.doctorId); const req = state.requirements.find((r) => r.id === eng.requirementId); const linkParams = new URLSearchParams({ stage: filter, candidateId: eng.id, ...(query ? { q: query } : {}) }); return <tr key={eng.id} className={selected === eng.id ? "is-selected" : ""}><td data-label="Doctor"><Link href={`?${linkParams.toString()}`}><span className="df-avatar small">{doctor?.initials}</span><strong>{doctor?.name}</strong></Link></td><td data-label="Vacancy">{req?.title}</td><td data-label="Origin">{eng.origins.map(stage).join(" + ")}</td><td data-label="Dates">{eng.selectedOccurrenceIds.length}</td><td data-label="Stage"><Status tone={eng.stage === "offer_sent" ? "info" : eng.stage === "shortlisted" ? "success" : "neutral"}>{stage(eng.stage)}</Status></td><td data-label="Last activity">{eng.lastContactAt ? date(eng.lastContactAt) : "No contact"}</td></tr> })}</tbody></table>{!engagements.length && <Empty title="No candidates match" detail="Clear the search or stage filter to see active candidates." />}</section>
      {selectedEng && <CandidateDetail state={state} engagement={selectedEng} busy={busy} command={command} closeHref={filterHref(filter)} />}</div></>
}

function Offers({ state, actor }: { state: WorkspaceState; actor: WorkspaceUser }) {
  const scopedEngagements = state.engagements.filter((eng) => state.requirements.find((req) => req.id === eng.requirementId)?.organisationId === actor.organisationId)
  const engagementIds = new Set(scopedEngagements.map((eng) => eng.id)); const offers = state.offers.filter((offer) => engagementIds.has(offer.engagementId))
  return <><PageTitle eyebrow="Hiring workspace" title="Offers" detail={`${offers.length} structured offer versions with an immutable audit trail.`} /><HiringNav actor={actor} active="offers" /><section className="df-panel df-table-panel"><GroupHeader tone="green" title="Offer register" count={offers.length} /><table className="df-table df-responsive-table"><thead><tr><th>Doctor</th><th>Vacancy</th><th>Version</th><th>Value</th><th>Expires</th><th>Status</th></tr></thead><tbody>{offers.map((offer) => { const eng = state.engagements.find((item) => item.id === offer.engagementId); const doctor = state.doctors.find((item) => item.id === eng?.doctorId); const req = state.requirements.find((item) => item.id === eng?.requirementId); return <tr key={offer.id}><td data-label="Doctor"><Link href={`/offers/${offer.id}`}><span className="df-avatar small">{doctor?.initials}</span><strong>{doctor?.name}</strong></Link></td><td data-label="Vacancy">{req?.title}</td><td data-label="Version">Version {offer.version}</td><td data-label="Value">{money(offer.totalMinor)}</td><td data-label="Expires">{date(offer.expiresAt)}</td><td data-label="Status"><Status tone={offer.status === "accepted" ? "success" : offer.status === "sent" ? "info" : "neutral"}>{stage(offer.status)}</Status></td></tr> })}</tbody></table>{!offers.length && <Empty title="No offers yet" detail="Structured offers will appear here after a candidate reaches discussion." />}</section></>
}

function CandidateDetail({ state, engagement, busy, command, closeHref }: { state: WorkspaceState; engagement: CandidateEngagement; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown>; closeHref: string }) {
  const doctor = state.doctors.find((item) => item.id === engagement.doctorId); const req = state.requirements.find((item) => item.id === engagement.requirementId)
  const currentOffer = state.offers.filter((item) => item.engagementId === engagement.id).toSorted((a, b) => b.version - a.version)[0]
  return <aside className="df-detail" aria-label="Candidate details"><div className="df-detail-head"><div><span className="df-avatar">{doctor?.initials}</span><div><span>Candidate record</span><h2>{doctor?.name}</h2><p>{doctor?.specialty} · {doctor?.baseArea}</p></div></div><Link href={closeHref} aria-label="Close candidate details"><LogOut size={19} /></Link></div><div className="df-detail-tabs"><span className="active">Overview</span><Link href={`/engagements/${engagement.id}`}>Conversation</Link><span>Checks</span><span>Activity</span></div><div className="df-detail-body"><Status tone="info">{stage(engagement.stage)}</Status><h3>{req?.title}</h3><p>{engagement.selectedOccurrenceIds.length} selected occurrence(s) · {engagement.origins.map(stage).join(" and ")}</p><EngagementLifecycle state={state} engagement={engagement} /><dl><div><dt>Expected rate</dt><dd>{doctor && money(doctor.expectedRateMinor)} / session</dd></div><div><dt>Availability</dt><dd>{doctor && stage(doctor.availabilityState)}</dd></div><div><dt>Evidence</dt><dd>{doctor?.evidenceSummary}</dd></div></dl><div className="df-note"><ShieldCheck size={18} /><p>Fit is explained from matching facts. Doc+Find does not score clinical competence.</p></div></div><div className="df-detail-actions"><Link className="df-secondary" href={`/engagements/${engagement.id}`}><MessageSquare size={17} /> Message</Link>{engagement.stage === "applied" && <button disabled={busy} className="df-primary" type="button" onClick={() => command("shortlist", engagement.id, engagement.version)}>Shortlist</button>}{engagement.stage === "shortlisted" && <button disabled={busy} className="df-primary" type="button" onClick={() => command("start-discussion", engagement.id, engagement.version)}>Start discussion</button>}{engagement.stage === "in_discussion" && doctor && req && <OfferComposer engagement={engagement} doctor={doctor} requirement={req} busy={busy} command={command} />}{engagement.stage === "offer_sent" && currentOffer && <Link className="df-primary" href={`/offers/${currentOffer.id}`}>View offer</Link>}{engagement.stage === "terms_accepted" && <span className="df-waiting">Terms accepted · readiness tracked separately</span>}</div></aside>
}

function OfferComposer({ engagement, doctor, requirement, busy, command }: { engagement: CandidateEngagement; doctor: WorkspaceState["doctors"][number]; requirement: WorkspaceState["requirements"][number]; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const [open, setOpen] = useState(false); const [rate, setRate] = useState(String(doctor.expectedRateMinor / 100)); const [paymentTerms, setPaymentTerms] = useState("Payment due within 30 days of invoice")
  async function sendOffer() { const result = await command("send-offer", engagement.id, engagement.version, { occurrenceIds: engagement.selectedOccurrenceIds, rateMinor: Number(rate) * 100, paymentTerms }); if ((result as { success?: boolean })?.success) setOpen(false) }
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="df-primary" type="button">Create offer</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="df-dialog-overlay" /><Dialog.Content className="df-form-dialog"><Dialog.Title>Offer terms for {doctor.name}</Dialog.Title><Dialog.Description>These terms become an immutable version after sending.</Dialog.Description><Dialog.Close className="df-dialog-close" aria-label="Close offer form"><X size={20} /></Dialog.Close><div className="df-offer-summary"><span>{requirement.title}</span><strong>{engagement.selectedOccurrenceIds.length} selected session(s)</strong></div><div className="df-dialog-form"><label>Rate per session<div className="df-money-input"><span>£</span><input inputMode="numeric" type="number" min="100" value={rate} onChange={(event) => setRate(event.target.value)} /></div></label><label>Payment terms<input value={paymentTerms} onChange={(event) => setPaymentTerms(event.target.value)} /></label><div className="df-dialog-note"><ShieldCheck size={17} /><span>Sending an offer does not accept it or make the doctor ready to work.</span></div><button disabled={busy || !rate} className="df-primary" type="button" onClick={sendOffer}>{busy ? "Sending…" : `Send ${money(Number(rate) * 100)} offer`}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}

function Doctors({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const [query, setQuery] = useState(""); const req = state.requirements.find((item) => item.organisationId === actor.organisationId && item.status === "published")
  const doctors = state.doctors.filter((item) => item.discoverable && `${item.name} ${item.specialty} ${item.baseArea}`.toLowerCase().includes(query.toLowerCase()))
  return <><PageTitle eyebrow="Doctor directory" title="Discover doctors" detail={`Search in context of ${req?.title ?? "an open vacancy"}. Availability is never inferred.`} /><div className="df-filterbar"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Search doctor directory" placeholder="Name, specialty or location" /><span className="df-filter-pill">Dermatology</span><span className="df-filter-pill">London</span></div><div className="df-card-grid">{doctors.map((doctor) => <article className="df-doctor-card" key={doctor.id}><div><span className="df-avatar">{doctor.initials}</span><div><h2>{doctor.name}</h2><p>{doctor.specialty} · {doctor.baseArea}</p></div></div><Status tone={doctor.availabilityState === "confirmed" ? "success" : "warning"}>{doctor.availabilityState === "unknown" ? "Needs confirmation" : `${stage(doctor.availabilityState)} availability`}</Status><ul><li>{doctor.experience}</li><li>{doctor.evidenceSummary}</li><li>{doctor.availableOccurrenceIds.length} matching date(s)</li></ul><footer><strong>{money(doctor.expectedRateMinor)} <small>/ session</small></strong>{req && <button disabled={busy} type="button" className="df-primary" onClick={() => command("invite", req.id, req.version, { doctorId: doctor.id })}>Invite</button>}</footer></article>)}</div></>
}

function DoctorToday({ state, actor }: { state: WorkspaceState; actor: WorkspaceUser }) {
  const notification = state.notifications.find((item) => item.recipientId === actor.id && !item.readAt)
  const doctorEngagements = state.engagements.filter((item) => item.doctorId === actor.id)
  const focusEngagement = doctorEngagements.find((item) => item.stage === "offer_sent" || item.stage === "terms_accepted") ?? doctorEngagements[0]
  return <><PageTitle eyebrow="Doctor workspace" title={`Good afternoon, ${actor.name.replace(/^Dr /, "").split(" ")[0]}`} detail="One clear next action, then your upcoming work." />{notification ? <section className="df-priority"><div><span className="df-kicker">Action needed</span><h2>{notification.title}</h2><p>{notification.detail}. Reviewing the offer does not accept it.</p></div><Link className="df-primary" href={notification.href}>Review safely <ChevronRight size={17} /></Link></section> : <section className="df-priority success"><div><span className="df-kicker">Up to date</span><h2>No urgent actions</h2><p>Your accepted terms and readiness checks remain visible separately.</p></div></section>}{focusEngagement && <section className="df-panel df-lifecycle-panel"><div className="df-section-head"><div><span>Current journey</span><h2>{state.requirements.find((item) => item.id === focusEngagement.requirementId)?.title}</h2></div><Link href={`/engagements/${focusEngagement.id}`}>Open details</Link></div><EngagementLifecycle state={state} engagement={focusEngagement} /></section>}<div className="df-grid-2"><section className="df-panel"><div className="df-section-head"><div><span>Active opportunities</span><h2>Your conversations</h2></div></div>{doctorEngagements.map((eng) => { const req = state.requirements.find((item) => item.id === eng.requirementId); return <Link className="df-record" href={`/engagements/${eng.id}`} key={eng.id}><div><strong>{req?.title}</strong><span>{eng.selectedOccurrenceIds.length} date(s) · {stage(eng.stage)}</span></div><ChevronRight size={18} /></Link> })}</section><section className="df-panel"><div className="df-section-head"><div><span>Readiness</span><h2>Checks remain specific</h2></div></div><div className="df-note"><ShieldCheck size={20} /><p>Being accepted does not mean ready to work. Site and scope approval are calculated for each session.</p></div></section></div></>
}

function FindWork({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) {
  const opportunities = state.requirements.filter((item) => item.status === "published"); const [selected, setSelected] = useState<Record<string, string[]>>({})
  return <><PageTitle eyebrow="Opportunities" title="Find work" detail="Select only the dates you can cover. Your application preserves those exact dates." /><div className="df-opportunities">{opportunities.map((req) => { const site = state.sites.find((item) => item.id === req.siteId); const chosen = selected[req.id] ?? []; const already = state.engagements.find((item) => item.requirementId === req.id && item.doctorId === actor.id); return <article className="df-panel df-opportunity" key={req.id}><div><Status tone="info">{req.specialty}</Status><h2>{req.title}</h2><p>{site?.name} · {site?.area}</p></div><strong className="df-rate">{money(req.rateMinor)} <small>/ session</small></strong><p>{req.workload}. {req.support}.</p><fieldset><legend>Choose available dates</legend>{req.occurrenceIds.map((id) => { const occ = state.occurrences.find((item) => item.id === id); return <label key={id}><input type="checkbox" checked={chosen.includes(id)} onChange={() => setSelected((current) => ({ ...current, [req.id]: chosen.includes(id) ? chosen.filter((value) => value !== id) : [...chosen, id] }))} /><span>{occ && date(occ.startsAt)}</span></label> })}</fieldset>{already ? <Link className="df-secondary" href={`/engagements/${already.id}`}>View {stage(already.stage)}</Link> : <button disabled={busy || !chosen.length} className="df-primary" type="button" onClick={() => command("apply", req.id, req.version, { occurrenceIds: chosen })}>Apply for {chosen.length || "selected"} date{chosen.length === 1 ? "" : "s"}</button>}</article> })}</div></>
}

function Bookings({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) { const bookings = state.bookings.filter((item) => item.doctorId === actor.id); return <><PageTitle eyebrow="Schedule" title="Bookings" detail="Agreement and permission to work remain separate for every occurrence." />{bookings.length ? bookings.map((booking) => { const payment = state.payments.find((item) => item.bookingId === booking.id); const complete = booking.occurrenceIds.every((id) => state.occurrences.find((item) => item.id === id)?.state === "completed"); return <section className="df-panel df-booking-card" key={booking.id}>{booking.occurrenceIds.map((id) => { const ready = calculateOccurrenceReadiness(state, actor.id, id); const occ = state.occurrences.find((item) => item.id === id); return <div className="df-record" key={id}><div><strong>{occ && date(occ.startsAt)}</strong><span>Terms accepted · {occ && stage(occ.state)} · Europe/London</span></div><Status tone={ready.state === "ready" ? "success" : "warning"}>{stage(ready.state)}</Status></div> })}<footer>{payment ? <Status tone={payment.state === "paid" ? "success" : payment.state === "discrepancy" ? "danger" : "info"}>Invoice: {stage(payment.state)}</Status> : complete ? <button disabled={busy} className="df-primary" type="button" onClick={() => command("submit-invoice", booking.id, booking.version, { invoiceReference: `DF-${booking.id.slice(-6).toUpperCase()}` })}>Submit invoice</button> : <span>Invoice becomes available after clinic-confirmed completion.</span>}</footer></section> }) : <Empty title="No accepted bookings yet" detail="An offer must be explicitly accepted before dates appear here." />}</> }

function ClinicBookings({ state, actor, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) { const engagementIds = new Set(state.engagements.filter((eng) => state.requirements.find((req) => req.id === eng.requirementId)?.organisationId === actor.organisationId).map((eng) => eng.id)); const bookings = state.bookings.filter((item) => engagementIds.has(item.engagementId)); return <><PageTitle eyebrow="Clinic schedule" title="Bookings" detail="Accepted agreements with a separate operational readiness state." />{bookings.length ? <section className="df-panel">{bookings.flatMap((booking) => booking.occurrenceIds.map((id) => { const occurrence = state.occurrences.find((item) => item.id === id); const doctor = state.doctors.find((item) => item.id === booking.doctorId); const readiness = calculateOccurrenceReadiness(state, booking.doctorId, id); const canComplete = occurrence?.state === "booked" && readiness.state === "ready" && new Date(occurrence.endsAt) <= new Date(); return <div className="df-record" key={id}><div><strong>{doctor?.name} · {occurrence && date(occurrence.startsAt)}</strong><span>Terms accepted · {occurrence && stage(occurrence.state)} · readiness assessed independently</span></div><div className="df-record-actions"><Status tone={readiness.state === "ready" ? "success" : "warning"}>{stage(readiness.state)}</Status>{canComplete && <button disabled={busy} className="df-secondary compact" type="button" onClick={() => command("mark-complete", id, occurrence.version)}>Confirm completion</button>}</div></div> }))}</section> : <Empty title="No accepted bookings yet" detail="Accepted offers will appear here without hiding unresolved readiness checks." />}</> }

function InboxView({ state, actor }: { state: WorkspaceState; actor: WorkspaceUser }) {
  const conversations = state.conversations.filter((item) => item.participantIds.includes(actor.id)).toSorted((a, b) => { const aTime = state.messages.filter((item) => item.conversationId === a.id).at(-1)?.sentAt ?? ""; const bTime = state.messages.filter((item) => item.conversationId === b.id).at(-1)?.sentAt ?? ""; return bTime.localeCompare(aTime) })
  const notifications = state.notifications.filter((item) => item.recipientId === actor.id).toSorted((a, b) => b.createdAt.localeCompare(a.createdAt))
  return <><PageTitle eyebrow="Communication centre" title="Inbox" detail={`${conversations.length} conversations and ${notifications.filter((item) => !item.readAt).length} unread updates.`} /><div className="df-inbox-layout"><section className="df-panel"><div className="df-section-head"><div><span>Messages</span><h2>Staffing conversations</h2></div></div>{conversations.map((conversation) => { const eng = state.engagements.find((item) => item.id === conversation.engagementId); const other = state.users.find((item) => conversation.participantIds.includes(item.id) && item.id !== actor.id); const latest = state.messages.filter((item) => item.conversationId === conversation.id).at(-1); const unread = state.messages.some((item) => item.conversationId === conversation.id && item.senderId !== actor.id && !item.seenBy[actor.id]); return <Link className={`df-record df-message-preview ${unread ? "unread" : ""}`} href={`/engagements/${eng?.id}`} key={conversation.id}><span className="df-avatar small">{other?.initials}</span><div><strong>{other?.name}{unread && <i>New</i>}</strong><span>{latest?.body ?? "No messages yet"}</span></div><time>{latest && date(latest.sentAt)}</time></Link> })}</section><aside className="df-panel df-notification-list"><div className="df-section-head"><div><span>Updates</span><h2>Activity requiring attention</h2></div></div>{notifications.map((item) => <Link className={`df-notification-item ${item.readAt ? "" : "unread"}`} href={item.href} key={item.id}><span className={`df-notification-icon ${item.category}`}><Bell size={16} /></span><div><strong>{item.title}</strong><p>{item.detail}</p><time>{date(item.createdAt)}{item.readAt ? ` · Seen ${date(item.readAt)}` : " · Unread"}</time></div><ChevronRight size={17} /></Link>)}</aside></div></>
}

function EngagementView({ state, actor, engagementId, onRefresh }: { state: WorkspaceState; actor: WorkspaceUser; engagementId: string; onRefresh: () => Promise<void> }) {
  const eng = state.engagements.find((item) => item.id === engagementId); const conversation = state.conversations.find((item) => item.engagementId === engagementId); const [body, setBody] = useState(""); const [price, setPrice] = useState(""); const [sending, setSending] = useState(false)
  const conversationId = conversation?.id
  const messages = state.messages.filter((item) => item.conversationId === conversationId)
  useEffect(() => { if (conversationId) void fetch(`/api/v1/conversations/${conversationId}/seen`, { method: "POST" }).then(onRefresh) }, [conversationId, onRefresh])
  if (!eng || !conversation || !conversation.participantIds.includes(actor.id)) return <Empty title="Record unavailable" detail="This engagement does not exist or is outside your authorised workspace." />
  const req = state.requirements.find((item) => item.id === eng.requirementId); const other = state.users.find((item) => conversation.participantIds.includes(item.id) && item.id !== actor.id)
  async function send() { if (!body.trim()) return; setSending(true); const response = await fetch(`/api/v1/conversations/${conversationId}/messages`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body, proposedRateMinor: price ? Number(price) * 100 : undefined }) }); if (response.ok) { setBody(""); setPrice(""); await onRefresh() } setSending(false) }
  return <><PageTitle eyebrow={req?.title ?? "Engagement"} title={other?.name ?? "Conversation"} detail={`${stage(eng.stage)} · ${eng.selectedOccurrenceIds.length} selected date(s)`} /><section className="df-panel df-conversation-context"><div><span>Shared staffing journey</span><strong>{req?.title}</strong></div><EngagementLifecycle state={state} engagement={eng} /></section><div className="df-message-layout"><section className="df-thread" aria-label="Conversation messages" aria-live="polite"><header><div><span className="df-avatar small">{other?.initials}</span><div><strong>{other?.name}</strong><small>{messages.length} message{messages.length === 1 ? "" : "s"} in this engagement</small></div></div><Status tone="success">Secure workspace</Status></header>{messages.map((message) => { const mine = message.senderId === actor.id; const seen = Object.entries(message.seenBy).find(([id]) => id !== actor.id); return <div className={`df-bubble ${mine ? "mine" : ""}`} key={message.id}><span>{state.users.find((item) => item.id === message.senderId)?.name}</span><p>{message.body}</p>{message.proposedRateMinor && <div className="df-proposal"><CircleDollarSign size={17} /><div><strong>{money(message.proposedRateMinor)} per session</strong><small>Price proposal only. This is not an accepted offer.</small></div></div>}<small>{date(message.sentAt)}{mine && seen ? ` · Seen ${date(seen[1])}` : mine ? " · Delivered" : ""}</small></div> })}</section><aside className="df-composer"><h2>Reply in context</h2><p>Send one message with an optional session price.</p><textarea aria-label="Message" value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a clear staffing message" /><label>Proposed price per session <div><span>£</span><input inputMode="numeric" type="number" min="1" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="Optional" /></div></label><button disabled={sending || !body.trim()} className="df-primary" type="button" onClick={send}>{sending ? "Sending…" : "Send message"}</button><small>Messages are visible to the doctor and authorised clinic participants. Clinical evidence is shared separately.</small></aside></div></>
}

function OfferView({ state, actor, offerId, busy, command }: { state: WorkspaceState; actor: WorkspaceUser; offerId: string; busy: boolean; command: (name: string, id: string, version: number) => Promise<unknown> }) {
  const offer = state.offers.find((item) => item.id === offerId); const eng = state.engagements.find((item) => item.id === offer?.engagementId); const req = state.requirements.find((item) => item.id === eng?.requirementId)
  if (!offer || !eng || !req || (actor.role === "doctor" ? eng.doctorId !== actor.id : actor.organisationId !== req.organisationId)) return <Empty title="Offer unavailable" detail="It may have changed or be outside your authorised workspace." />
  const readiness = calculateOccurrenceReadiness(state, eng.doctorId, offer.occurrenceIds[0])
  return <><PageTitle eyebrow={`${req.title} · Offer version ${offer.version}`} title="Review offer" detail="Reviewing this page does not accept the offer." /><section className="df-panel df-lifecycle-panel"><div className="df-section-head"><div><span>Shared progress</span><h2>From interest to payment</h2></div></div><EngagementLifecycle state={state} engagement={eng} /></section><div className="df-offer-layout"><section className="df-panel df-offer"><div className="df-offer-total"><div><span>Total for {offer.occurrenceIds.length} session(s)</span><strong>{money(offer.totalMinor)}</strong></div><Status tone={offer.status === "sent" ? "info" : offer.status === "accepted" ? "success" : "neutral"}>{stage(offer.status)}</Status></div><dl><div><dt>Scope</dt><dd>{offer.scope}</dd></div><div><dt>Payer</dt><dd>{offer.payer}</dd></div><div><dt>Session rate</dt><dd>{money(offer.rateMinor)}</dd></div><div><dt>Payment</dt><dd>{offer.paymentTerms}</dd></div><div><dt>Cancellation</dt><dd>{offer.cancellationTerms}</dd></div><div><dt>Expires</dt><dd>{date(offer.expiresAt)}</dd></div></dl><h2>Included occurrences</h2>{offer.occurrenceIds.map((id) => { const occ = state.occurrences.find((item) => item.id === id); return <div className="df-record" key={id}><CalendarDays size={18} /><div><strong>{occ && date(occ.startsAt)}</strong><span>Europe/London · {req.scope}</span></div></div> })}</section><aside className="df-panel df-decision"><h2>Decision</h2><p>Terms acceptance and readiness are deliberately separate.</p><Status tone={readiness.state === "ready" ? "success" : "warning"}>{stage(readiness.state)}</Status>{readiness.blockers.map((blocker) => <p className="df-blocker" key={blocker}>{blocker}</p>)}{actor.role === "doctor" && offer.status === "sent" ? <><button disabled={busy} className="df-primary" type="button" onClick={() => command("accept-offer", offer.id, offer.version)}>Accept displayed version</button><Link className="df-secondary" href={`/engagements/${eng.id}`}>Ask a question</Link><button disabled={busy} className="df-text-button danger" type="button" onClick={() => command("decline-offer", offer.id, offer.version)}>Decline offer</button></> : <p className="df-waiting">{actor.role === "doctor" ? "No decision is available for this version." : "Only the named doctor can accept this offer."}</p>}</aside></div></>
}

function ApproverView({ state, busy, command }: { state: WorkspaceState; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) { return <><PageTitle eyebrow="Clinical governance" title="My reviews" detail="Approval remains bound to doctor, site, scope, and validity period." /><section className="df-panel">{state.approvals.map((approval) => <div className="df-record" key={approval.id}><div><strong>{state.doctors.find((item) => item.id === approval.doctorId)?.name}</strong><span>{state.sites.find((item) => item.id === approval.siteId)?.name} · {approval.scope}</span></div><div className="df-record-actions"><Status tone={approval.status === "approved" ? "success" : "warning"}>{stage(approval.status)}</Status>{approval.status !== "approved" && <button disabled={busy} type="button" className="df-secondary compact" onClick={() => command("approve-scope", approval.id, approval.version, { rationale: "Evidence reviewed for the named site and scope" })}>Approve scope</button>}</div></div>)}</section></> }
function FinanceView({ state, busy, command }: { state: WorkspaceState; busy: boolean; command: (name: string, id: string, version: number, payload?: Record<string, unknown>) => Promise<unknown> }) { return <><PageTitle eyebrow="Finance" title="Reconciliation" detail="Completion, invoice submission, and payment confirmation remain separate events." /><section className="df-panel">{state.payments.length ? state.payments.map((payment) => <div className="df-record" key={payment.id}><div><strong>{money(payment.amountMinor)}</strong><span>{payment.invoiceReference ?? "Invoice not submitted"}</span></div><div className="df-record-actions"><Status tone={payment.state === "paid" ? "success" : payment.state === "discrepancy" ? "danger" : "info"}>{stage(payment.state)}</Status>{(payment.state === "due" || payment.state === "processing") && <button disabled={busy} className="df-secondary compact" type="button" onClick={() => command("confirm-payment", payment.id, payment.version)}>Confirm payment</button>}</div></div>) : <Empty title="Nothing ready to reconcile" detail="A completed session must be confirmed before an invoice becomes due." />}</section></> }
function OperationsView({ state }: { state: WorkspaceState }) { return <><PageTitle eyebrow="Operations" title="Cases and audit" detail="A factual history of material actions across the fictional workspace." /><section className="df-panel">{state.auditEvents.toReversed().map((event) => <div className="df-record" key={event.id}><div><strong>{stage(event.action)}</strong><span>{event.detail} · {date(event.at)}</span></div><Status>v{event.version}</Status></div>)}</section></> }

function OnboardingView({ state, actor, audience, onRefresh }: { state: WorkspaceState; actor: WorkspaceUser; audience: "doctor" | "clinic"; onRefresh: () => Promise<void> }) {
  const existing = state.onboardingDrafts.find((item) => item.userId === actor.id && item.audience === audience); const [fields, setFields] = useState(existing?.fields ?? {}); const [step, setStep] = useState(existing?.step ?? 1); const [saved, setSaved] = useState(false)
  const steps = audience === "doctor" ? ["Professional scope", "Services", "Availability", "Evidence", "Preferences"] : ["Organisation", "Clinic sites", "Services", "Clinical review", "Finance"]
  const fieldDefinitions = audience === "doctor" ? [{ key: "specialty", label: "Specialty", placeholder: "Dermatology" }, { key: "baseArea", label: "Professional base", placeholder: "London" }, { key: "services", label: "Services and scope", placeholder: "Adult outpatient dermatology" }, { key: "rate", label: "Expected session rate", placeholder: "600" }, { key: "availability", label: "Availability pattern", placeholder: "Tuesdays and alternate Saturdays" }, { key: "contactPreference", label: "Preferred first contact", placeholder: "Messages first" }] : [{ key: "organisation", label: "Organisation name", placeholder: "Clinic legal or trading name" }, { key: "site", label: "Primary site", placeholder: "Site name and area" }, { key: "service", label: "Dermatology services", placeholder: "Adult outpatient dermatology" }, { key: "facilities", label: "Facilities and support", placeholder: "Nurse, room and administration" }, { key: "approver", label: "Clinical approver", placeholder: "Named clinical reviewer" }, { key: "finance", label: "Finance contact", placeholder: "Named finance owner" }]
  async function save(nextStep = step) { const response = await fetch(`/api/v1/onboarding/${audience}`, { method: "PUT", headers: { "content-type": "application/json", "Expected-Version": String(existing?.version ?? 0) }, body: JSON.stringify({ step: nextStep, fields }) }); if (response.ok) { setSaved(true); setStep(nextStep); await onRefresh() } }
  return <><PageTitle eyebrow="Onboarding" title={audience === "doctor" ? "Professional profile" : "Clinic account"} detail="Save and resume without implying evidence verification or site approval." /><div className="df-onboarding-layout"><aside className="df-panel df-onboarding-steps"><div><strong>{Math.round((step / steps.length) * 100)}%</strong><span>Profile progress</span></div><ol>{steps.map((label, index) => <li className={index + 1 < step ? "complete" : index + 1 === step ? "current" : ""} key={label}><span>{index + 1 < step ? <Check size={13} /> : index + 1}</span><button type="button" onClick={() => setStep(index + 1)}>{label}</button></li>)}</ol></aside><section className="df-panel df-form"><div className="df-progress"><span style={{ width: `${Math.min(100, (step / steps.length) * 100)}%` }} /></div><div className="df-form-status"><Status tone={existing?.status === "approved" ? "success" : "warning"}>{stage(existing?.status ?? "draft")}</Status><span>Step {step} of {steps.length}: {steps[step - 1]}</span></div>{fieldDefinitions.map((field) => <label key={field.key}>{field.label}<input value={fields[field.key] ?? ""} placeholder={field.placeholder} onChange={(event) => { setSaved(false); setFields({ ...fields, [field.key]: event.target.value }) }} /></label>)}<div className="df-dialog-note"><ShieldCheck size={17} /><span>Profile completeness, evidence checks, site approval and readiness are recorded separately.</span></div><div className="df-form-actions"><button type="button" className="df-secondary" onClick={() => save(step)}>{saved ? "Saved" : "Save and continue later"}</button><button type="button" className="df-primary" onClick={() => save(Math.min(steps.length, step + 1))}>{step === steps.length ? "Save profile" : "Save and next step"}</button></div></section></div></>
}
